### ISSUE TITLE
mình mở tool lên chạy quyền admin nhưng mà không thấy lên điểm

### ISSUE THREAD

**Issue by jaypham123** [t-rekttt/lolsn#10]
mình mở tool lên chạy quyền admin nhưng check game thì không thấy điểm lên hay gì cả vẫn 0 điểm ạ 

![image](https://user-images.githubusercontent.com/88517900/128437587-ef481c6f-7383-48c4-8c04-8421f6735525.png)

**Comment by t-rekttt** [comment]
Mình mới fix, bạn down code mới và chạy lại thử xem
