### ISSUE TITLE
Chào bạn t-rekttt đẹp trai

### ISSUE THREAD

**Issue by TVMD** [t-rekttt/lolsn#3]
Mình đã chạy thử script và nhập được bong bóng. Mình có thắc mắc là cái list code lấy ở đâu ra. 
Nếu tiện thì join group tele này chỉ mình với nhé : t.me/lolsnxx ( có mình với 1 con bot thôi)

**Comment by t-rekttt** [comment]
List code mình lấy từ repo của 1 bạn khác,, mình có ghi ở README
