### ISSUE TITLE
Convert sang ngôn ngữ khác bị lỗi bad_request

### ISSUE THREAD

**Issue by g2asell2019** [t-rekttt/lolsn#4]
Mình có thử chuyển từ request trong python sang ngôn ngữ khác như autoit hay tool request như postman thì bị lỗi 

> {"error": "ERROR__BAD_REQUEST"}

Code AutoIT : [http://collabedit.com/q6rj3](url)

Code Python : [http://collabedit.com/48d57](url)

Mình có thử vài trường hợp sai header hay token thì nó đều trả về là bad request

Còn bên python thì mình sai như bên các ngôn ngữ khác thì nó trả về : 

> {'error': 'ERROR__SERVER_ERROR'}

Cảm ơn bạn đã đọc <3

**Comment by nomi-san** [comment]
> {"error": "ERROR__BAD_REQUEST"}
Code AutoIT : http://collabedit.com/q6rj3

Do thiếu header 🙂

> {'error': 'ERROR__SERVER_ERROR'}
Code Python : http://collabedit.com/48d57

Do sai token 🙂

**Comment by g2asell2019** [comment]
> Do thiếu header 🙂
bạn có thể chỉ mình thiếu header phần nào được không bạn 

> Code AutoIT : http://collabedit.com/q6rj3
phần này thì mình có thiếu UA, mình có sửa lại nhưng response vẫn là bad_request

còn lại là vẫn giống bên python, bên python thì chạy bình thường

[http://collabedit.com/b4yw7](url)


> Do sai token 🙂
>Còn bên python thì mình sai như bên các ngôn ngữ khác thì nó trả về
>{'error': 'ERROR__SERVER_ERROR'}

Như trên mình có nói là mình có thử sai xem nó response là cái gì thì 2 thằng response khác nhau

Cả 2 bên đều sai token:

+ Python response là >{'error': 'ERROR__SERVER_ERROR'}

+ Autoit có token trong header hay UA đều trả về > {"error": "ERROR__BAD_REQUEST"}

**Comment by t-rekttt** [comment]
> Mình có thử chuyển từ request trong python sang ngôn ngữ khác như autoit hay tool request như postman thì bị lỗi
> 
> > {"error": "ERROR__BAD_REQUEST"}
> 
> Code AutoIT : [http://collabedit.com/q6rj3](url)
> 
> Code Python : [http://collabedit.com/48d57](url)
> 
> Mình có thử vài trường hợp sai header hay token thì nó đều trả về là bad request
> 
> Còn bên python thì mình sai như bên các ngôn ngữ khác thì nó trả về :
> 
> > {'error': 'ERROR__SERVER_ERROR'}
> 
> Cảm ơn bạn đã đọc <3

Hình như bạn chưa thêm header `Content-Type: application/json`

**Comment by g2asell2019** [comment]
Theo UDF của _HttpRequest.au3 thì content-type bạn không phải nạp nếu khác 3 loại dưới

![image](https://user-images.githubusercontent.com/51025883/128129231-9c450081-2fcf-4d91-9637-420eeb94dbab.png)

Link UDF: https://is.gd/CVIZjR

Mình cũng có thử nạp nhưng vẫn bị bad request 

![image](https://user-images.githubusercontent.com/51025883/128129426-7c56e056-11c7-48e8-91cd-30f04d75fa48.png)

**Comment by t-rekttt** [comment]
> Theo UDF của _HttpRequest.au3 thì content-type bạn không phải nạp nếu khác 3 loại dưới
> 
> ![image](https://user-images.githubusercontent.com/51025883/128129231-9c450081-2fcf-4d91-9637-420eeb94dbab.png)
> 
> Link UDF: https://is.gd/CVIZjR
> 
> Mình cũng có thử nạp nhưng vẫn bị bad request
> 
> ![image](https://user-images.githubusercontent.com/51025883/128129426-7c56e056-11c7-48e8-91cd-30f04d75fa48.png)

Cái JSON của bạn viết sai rồi, phải là `true` chứ không phải `True`. Bên python dùng `True` là vì đấy là boolean primitive của nó

**Comment by g2asell2019** [comment]
> Cái JSON của bạn viết sai rồi, phải là true chứ không phải True. Bên python dùng True là vì đấy là boolean primitive của nó

mình sửa được rồi  cảm ơn bạn nhiều <3


sai ở chỗ true chứ không phải True

![image](https://user-images.githubusercontent.com/51025883/128131741-f1e2bb1a-93e5-4449-88d5-40ba7716032f.png)

**Comment by g2asell2019** [comment]
![image](https://user-images.githubusercontent.com/51025883/128131705-4280b4fb-34a1-4f93-9888-3cded9b5a9b7.png)
