### ISSUE TITLE
expecting value

### ISSUE THREAD

**Issue by trbmngh** [t-rekttt/lolsn#7]
![image](https://user-images.githubusercontent.com/88413468/128110045-18aaa7f0-5e7d-4ee3-8166-29e59cff870c.png)

**Comment by g2asell2019** [comment]
client vẫn chạy khi tool đang chạy đúng không bạn

**Comment by t-rekttt** [comment]
Mình mới update code để in ra error traceback, bạn chạy lại rồi chụp lỗi giúp mình nhé
