### ISSUE TITLE
mình thực hiện chạy theo cách 1 mở file lolsn chạy với quyền admin rồi mà n lại báo lỗi này. Bạn xem thế nào nhé 

### ISSUE THREAD

**Issue by khaicm-0897** [t-rekttt/lolsn#9]
![image](https://user-images.githubusercontent.com/51064915/128212663-16619cbe-fbd8-4f4e-9964-6489679c4de8.png)

**Comment by t-rekttt** [comment]
Bạn tải thử vcredist_x64 tại đây xem: https://support.microsoft.com/vi-vn/topic/t%E1%BA%A3i-xu%E1%BB%91ng-phi%C3%AAn-b%E1%BA%A3n-visual-c-m%E1%BB%9Bi-nh%E1%BA%A5t-%C4%91%C6%B0%E1%BB%A3c-h%E1%BB%97-tr%E1%BB%A3-2647da03-1eea-4433-9aff-95f26a218cc0
Direct link: https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by khaicm-0897** [comment]
@t-rekttt thank you bạn, mình thử download lại bản build mới của bạn thì được luôn không cần tải gì cả
